
services:
  chainsync:
    image: mariusgeorgescu/chainsync:chainsync
    container_name: bjj-chainsync
    environment:
      - KUPO_URL=https://kupo16cdjk05emessgrpy45t.preview-v2.kupo-m1.demeter.run
      - LOOKUP_PATH=/data/chainsync.sqlite
      - BATCH_SIZE=100000000
      - FETCH_BATCH_SIZE=10000000
    volumes:
      - chainsync-db:/data
    healthcheck:
      test: ["CMD-SHELL", "test -f /data/chainsync.sqlite || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 5s
    restart: unless-stopped

  interaction-api:
    image: mariusgeorgescu/bjj-interaction-api:latest
    container_name: bjj-interaction-api
    environment:
      - PORT=8082
      - LOOKUP_PATH=/data/chainsync.sqlite
      # - BASIC_USER=cardano
      # - BASIC_PASS=lovelace
    volumes:
      - chainsync-db:/data
    ports:
      - "8082:8082"
    depends_on:
      chainsync:
        condition: service_healthy
    restart: unless-stopped
    command: ["/app/interaction-api"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8082/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 5s

  query-api:
    image: mariusgeorgescu/bjj-query-api:latest
    container_name: bjj-query-api
    environment:
      - PORT=8083
      - LOOKUP_PATH=/data/chainsync.sqlite
      # - BASIC_USER=cardano
      # - BASIC_PASS=lovelace
    volumes:
      - chainsync-db:/data
    ports:
      - "8083:8083"
    depends_on:
      chainsync:
        condition: service_healthy
    restart: unless-stopped
    command: ["/app/query-api"] 
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8083/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 5s

  nginx:
    image: nginx:1.27-alpine
    container_name: bjj-nginx
    depends_on:
      interaction-api:
        condition: service_healthy
      query-api:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-www:/var/www/certbot
      - letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    container_name: bjj-certbot
    entrypoint: sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h & wait $${!}; done;"
    volumes:
      - certbot-www:/var/www/certbot
      - letsencrypt:/etc/letsencrypt
    restart: unless-stopped

volumes:
  chainsync-db:
  certbot-www:
  letsencrypt:

